### PR TITLE
ADCM-2218 ADCM-2092 Bump base image

### PR DESCRIPTION
**Pull request by acmnu**
This PR do the following:
* Bumps ansible to 2.9.25
* Bumps Python to 3.10

### CODE REVIEW

**Comment by nagarin** [comment]
bender build

**Comment by BenderArenadata** [comment]
Hey, @nagarin! Build has been launched!

**Comment by nagarin** [comment]
bender build

**Comment by BenderArenadata** [comment]
Hey, @nagarin! Build has been launched!

**Comment by BenderArenadata** [comment]
Hey, @nagarin! Build has been launched!

**Comment by acmnu** [comment]
@dgusakov @skhomuti  I'd like to do a second go for this activity. Do we have a resources to test it?

**Comment by acmnu** [comment]
After troubles with ADQM we can't switch to 2.9.x so far. So I cancel this one in favor to future PR, which I believe will add a venv based ansible 2.9 along with ansible 2.12

Related PR's are: #1330 and https://github.com/arenadata/adcm_cluster_adqm/pull/197

**Pull request closed without merging**
