### PR TITLE
ADCM-3166 add case provider-host-config-restore

### PR DESCRIPTION
**Pull request by DanBalalan**

### CODE REVIEW

**Comment by DanBalalan** [comment]
bender build

**Comment by BenderArenadata** [comment]
Hey, @DanBalalan! Build has been launched!

**Review by a-alferov — APPROVED** [review]

**Comment by DanBalalan** [comment]
bender build

**Comment by BenderArenadata** [comment]
Hey, @DanBalalan! Build has been launched!

**Pull request merged**
