### PR TITLE
FIX pylint W1514(unspecified-encoding)

### PR DESCRIPTION
**Pull request by nagarin**

### CODE REVIEW

**Review by acmnu — DISMISSED** [review]

**Review by acmnu — DISMISSED** [review]

**Comment by nagarin** [comment]
bender build

**Comment by BenderArenadata** [comment]
Hey, @nagarin! Build has been launched!

**Comment by nagarin** [comment]
bender build

**Comment by BenderArenadata** [comment]
Hey, @nagarin! Build has been launched!

**Review by grey-kristy — APPROVED** [review]

**Pull request merged**
