### PR TITLE
ADCM-2498 ADCM-2537 Remove ADCM Administrator and retest everything.

### PR DESCRIPTION
**Pull request by acmnu**

### CODE REVIEW

**Comment by acmnu** [comment]
bender build

**Comment by BenderArenadata** [comment]
Hey, @acmnu! Build has been launched!

**Review by SofiaTal — COMMENTED** [review]
As mentioned in meeting git is not smart enough, so, your changes move to the over role. I think that application configuration shoul be parametrized by cluster, service and component. Fix for infrastructure configuration done in #1439

**Comment by acmnu** [comment]
@SofiaTal I already fixed this in 050fa88 before I saw your comment.

**Pull request merged**
