### PR TITLE
Refactor locks, get rid of obj.stack

### PR DESCRIPTION
**Pull request by nagarin**

### CODE REVIEW

**Comment by nagarin** [comment]
bender build

**Comment by BenderArenadata** [comment]
Hey, @nagarin! Build has been launched!

**Comment by nagarin** [comment]
bender build

**Comment by BenderArenadata** [comment]
Hey, @nagarin! Build has been launched!

**Comment by nagarin** [comment]
bender build

**Comment by BenderArenadata** [comment]
Hey, @nagarin! Build has been launched!

**Pull request merged**
