### PR TITLE
ADCM-2399 ADCM-2218 ADCM-2240 Bump python and separate image 

### PR DESCRIPTION
**Pull request by acmnu**
This PR do the following: 

* Move out base image assemble to separate repo areandata/adcm_base
* Bump Python to Python 3.10

This commit cancel #1202 

Related PR to base is https://github.com/arenadata/adcm_base/pull/1

### CODE REVIEW

**Comment by acmnu** [comment]
bender build

**Comment by BenderArenadata** [comment]
Hey, @acmnu! Build has been launched!

**Comment by acmnu** [comment]
bender build

**Comment by BenderArenadata** [comment]
Hey, @acmnu! Build has been launched!

**Review by dgusakov — COMMENTED** [review]
From this PR it is not obvious to what python version we actually move. @acmnu Pls provide a link to the corresponding PR in the new repo with the base image

**Comment by acmnu** [comment]
@dgusakov Check links above your message.

Direct link https://github.com/arenadata/adcm_base/pull/1

**Review by dgusakov — APPROVED** [review]

**Pull request merged**
