### PR TITLE
ADCM-2956 Fix action hc_acl, service is required

### PR DESCRIPTION
**Pull request by winmasta**

### CODE REVIEW

**Comment by a-alferov** [comment]
bender build

**Comment by BenderArenadata** [comment]
Hey, @a-alferov! Build has been launched!

**Comment by winmasta** [comment]
bender build

**Comment by BenderArenadata** [comment]
Hey, @winmasta! Build has been launched!

**Comment by winmasta** [comment]
bender build

**Comment by BenderArenadata** [comment]
Hey, @winmasta! Build has been launched!

**Comment by winmasta** [comment]
bender build

**Comment by BenderArenadata** [comment]
Hey, @winmasta! Build has been launched!

**Comment by winmasta** [comment]
bender build

**Comment by BenderArenadata** [comment]
Hey, @winmasta! Build has been launched!

**Comment by winmasta** [comment]
bender build

**Comment by BenderArenadata** [comment]
Hey, @winmasta! Build has been launched!

**Comment by winmasta** [comment]
bender build

**Comment by BenderArenadata** [comment]
Hey, @winmasta! Build has been launched!

**Comment by winmasta** [comment]
bender build

**Comment by BenderArenadata** [comment]
Hey, @winmasta! Build has been launched!

**Review by SofiaTal — APPROVED** [review]

**Pull request merged**
