### PR TITLE
ADCM-3035 Add multi_states to upgrade

### PR DESCRIPTION
**Pull request by kuhella**
https://tracker.yandex.ru/ADCM-3035

### CODE REVIEW

**Review by a-alferov — APPROVED** [review]

**Comment by kuhella** [comment]
bender build

**Comment by BenderArenadata** [comment]
Hey, @kuhella! Build has been launched!

**Comment by kuhella** [comment]
bender build

**Comment by BenderArenadata** [comment]
Hey, @kuhella! Build has been launched!

**Pull request merged**
