### PR TITLE
ADCM-2501 Added before upgrade info for Cluster and Provider

### PR DESCRIPTION
**Pull request by a-alferov**

### CODE REVIEW

**Review by kuhella — APPROVED** [review]

**Review by nagarin — DISMISSED** [review]

**Comment by a-alferov** [comment]
bender build

**Comment by BenderArenadata** [comment]
Hey, @a-alferov! Build has been launched!

**Review by alexterent — APPROVED** [review]

**Comment by a-alferov** [comment]
bender build

**Comment by BenderArenadata** [comment]
Hey, @a-alferov! Build has been launched!

**Pull request merged**
