### PR TITLE
ADCM-3011 - Save button should be enabled on group config page

### PR DESCRIPTION
**Pull request by dbardin90**
https://tracker.yandex.ru/ADCM-3011

### CODE REVIEW

**Review by remizov-arena — DISMISSED** [review]

**Review by remizov-arena — APPROVED** [review]

**Comment by kuhella** [comment]
bender build

**Comment by BenderArenadata** [comment]
Hey, @kuhella! Build has been launched!

**Comment by kuhella** [comment]
bender build

**Comment by BenderArenadata** [comment]
Hey, @kuhella! Build has been launched!

**Comment by kuhella** [comment]
bender build

**Comment by BenderArenadata** [comment]
Hey, @kuhella! Build has been launched!

**Comment by kuhella** [comment]
bender build

**Comment by BenderArenadata** [comment]
Hey, @kuhella! Build has been launched!

**Comment by kuhella** [comment]
bender build

**Comment by BenderArenadata** [comment]
Hey, @kuhella! Build has been launched!

**Review by kuhella — APPROVED** [review]

**Pull request merged**
