### PR TITLE
Release 2022.08.08

### PR DESCRIPTION
**Pull request by kuhella**

### CODE REVIEW

**Comment by kuhella** [comment]
bender build

**Comment by BenderArenadata** [comment]
Hey, @kuhella! Build has been launched!

**Comment by annademina** [comment]
bender build

**Comment by BenderArenadata** [comment]
Hey, @annademina! Build has been launched!

**Comment by kuhella** [comment]
bender build

**Comment by BenderArenadata** [comment]
Hey, @kuhella! Build has been launched!

**Review by a-alferov — APPROVED** [review]

**Pull request merged**
