### PR TITLE
ADCM-3221 Get rid of base docker image repo

### PR DESCRIPTION
**Pull request by winmasta**

### CODE REVIEW

**Comment by BenderArenadata** [comment]
Hey, @winmasta! Build has been launched!

**Comment by winmasta** [comment]
bender build

**Comment by BenderArenadata** [comment]
Hey, @winmasta! Build has been launched!

**Comment by winmasta** [comment]
bender build

**Comment by BenderArenadata** [comment]
Hey, @winmasta! Build has been launched!

**Comment by winmasta** [comment]
bender build

**Comment by BenderArenadata** [comment]
Hey, @winmasta! Build has been launched!

**Comment by winmasta** [comment]
bender build

**Comment by BenderArenadata** [comment]
Hey, @winmasta! Build has been launched!

**Comment by winmasta** [comment]
bender build

**Comment by BenderArenadata** [comment]
Hey, @winmasta! Build has been launched!

**Comment by winmasta** [comment]
bender build

**Comment by BenderArenadata** [comment]
Hey, @winmasta! Build has been launched!

**Comment by winmasta** [comment]
bender build

**Review by a-alferov — APPROVED** [review]

**Pull request merged**
