### PR TITLE
ADCM-3199 Fix host and cluster regex validator

### PR DESCRIPTION
**Pull request by winmasta**

### CODE REVIEW

**Review by a-alferov — APPROVED** [review]

**Comment by winmasta** [comment]
bender build

**Comment by BenderArenadata** [comment]
Hey, @winmasta! Build has been launched!

**Comment by winmasta** [comment]
bender build

**Comment by BenderArenadata** [comment]
Hey, @winmasta! Build has been launched!

**Comment by winmasta** [comment]
bender build

**Comment by BenderArenadata** [comment]
Hey, @winmasta! Build has been launched!

**Review by a-alferov — APPROVED** [review]

**Pull request merged**
