### PR TITLE
ADCM-3143 - [UI] Fix config sending for group-configs

### PR DESCRIPTION
**Pull request by kuhella**
https://tracker.yandex.ru/ADCM-3143

### CODE REVIEW

**Comment by kuhella** [comment]
bender build

**Comment by BenderArenadata** [comment]
Hey, @kuhella! Build has been launched!

**Review by dbardin90 — APPROVED** [review]

**Comment by kuhella** [comment]
bender build

**Comment by kuhella** [comment]
bender build

**Comment by BenderArenadata** [comment]
Hey, @kuhella! Build has been launched!

**Review by dbardin90 — APPROVED** [review]

**Pull request merged**
