### PR TITLE
ADCM-2902 - Expand Table view in User tab

### PR DESCRIPTION
**Pull request by dbardin90**
https://tracker.yandex.ru/ADCM-2902

### CODE REVIEW

**Comment by dbardin90** [comment]
Work done for https://tracker.yandex.ru/ADCM-2932 pushed here

**Comment by rimakan** [comment]
bender build

**Comment by BenderArenadata** [comment]
Hey, @rimakan! Build has been launched!

**Comment by BenderArenadata** [comment]
Hey, @rimakan! Build has been launched!

**Comment by BenderArenadata** [comment]
Hey, @remizov-arena! Build has been launched!

**Review by remizov-arena — APPROVED** [review]

**Pull request merged**
