### PR TITLE
Release 2021.05.25

### LINKED ISSUE #814: config for components
From manuals "Config Parameters - There are a number of user editable values that could be represented in UI and related to **every** object." (https://docs.arenadata.io/adcm/sdk/config.html#config-parameters)
But I have found that I cannot use config section for components.
There is no issues during config file validation, but the GUI obviously does not provide settings for the components.
Configuration example:

- name: fencing
  display_name: Cluster fencing
  type: service
  required: true
  description: "Add cluster fences"
  version: *version
  actions:
    add_fences: 
      display_name: Add fences
      script: pgsql_cluster/add_fences.yaml
      script_type: ansible
      type: job  
      states:
        available: 
          - prepared
        on_success: configured
        on_fail: prepared
      log_files: [check]
  components:
    fence:
      constraint: [+]
      display_name: fence
      config:
        ip:
          display_name: Fence device IP
          description: >
            Fence device IP
          type: string
          default: "1.1.1.1"
        tool: 
          display_name: Fencing tool
          description: >
            Fencing tool (default - tool from defaults parameters group)
          type: string
          required: false
          default: ""
        login: 
          display_name: Fencing device user login name
          description: >
            Fencing device user login name (default - login name from defaults parameters group)
          type: string
          required: false
          default: ""
        passwd: 
          display_name: Fencing device user password
          description: >
            Fencing device login name (default - password from defaults parameters group)
          type: string
          required: false
          default: ""
        options:
          display_name: Fencing device options
          description: >
            Fencing device options (default - options from defaults parameters group)
          type: string
          required: false
          default: ""
  config:
    __main_info:
      type: text
      default: >
        ..
    tool: 
      display_name: Default fencing tool
      description: >
        Default fencing tool
      type: string
      default: "fence_fake"
    login:
      display_name: Default fencing device user login name
      description: >
        Default fencing device user login name
      type: string
      default: "fence_user"
    passwd:
      display_name: Default fencing device user password
      description: >
        Default fencing device login name
      type: string
      default: "passw0rd"
    options:
      display_name: Default fencing device options
      description: >
        Default fencing device options
      type: string
      default: "lanplus=1 power_wait=1 delay=5 pcmk_monitor_retries=5 op monitor interval=300s name=monitor on-fail=restart timeout=240s"

### PR DESCRIPTION
**Pull request by acmnu**
## New Features

* Components as first class object (with config, and actions). Fix #814 
* New config type "variant" with sophisticated functions to provide list of variants.

### CODE REVIEW

**Comment by dgusakov** [comment]
@acmnu I guess we need to wait for bundle tests to be performed next night.

**Comment by acmnu** [comment]
@dgusakov ok I shall wait for Wednesday.

**Comment by acmnu** [comment]
This PR should fix #814

**Comment by acmnu** [comment]
bender build

**Comment by BenderArenadata** [comment]
Hey, @acmnu! Build has been launched!

**Review by dgusakov — APPROVED** [review]

**Pull request merged**
