### PR TITLE
ADCM-2205 Add ui-view on component status

### PR DESCRIPTION
**Pull request by SofiaTal**

### CODE REVIEW

**Comment by SofiaTal** [comment]
bender build

**Comment by BenderArenadata** [comment]
Hey, @SofiaTal! Build has been launched!

**Review by grey-kristy — APPROVED** [review]

**Review by grey-kristy — APPROVED** [review]

**Comment by SofiaTal** [comment]
bender build

**Comment by BenderArenadata** [comment]
Hey, @SofiaTal! Build has been launched!

**Pull request merged**
