### PR TITLE
ADCM-1712 removed vertical scrolling in run dialog

### PR DESCRIPTION
**Pull request by sanshan**

### CODE REVIEW

**Comment by acmnu** [comment]
bender build

**Comment by sanshan** [comment]
bender build

**Comment by BenderArenadata** [comment]
Hey, @sanshan! Build has been launched!

**Review by drKaramazin — APPROVED** [review]

**Comment by sanshan** [comment]
bender build

**Comment by BenderArenadata** [comment]
Hey, @sanshan! Build has been launched!

**Pull request merged**
