### PR TITLE
ADCM-2729 fix tests test_invoker_object_url and test_check_policy_pop…

### PR DESCRIPTION
**Pull request by annademina**
…up_for_entities

### CODE REVIEW

**Review by Sealwing — APPROVED** [review]

**Comment by annademina** [comment]
bender build

**Comment by BenderArenadata** [comment]
Hey, @annademina! Build has been launched!

**Comment by annademina** [comment]
bender build

**Comment by BenderArenadata** [comment]
Hey, @annademina! Build has been launched!

**Pull request merged**
