### PR TITLE
ADCM-3051 archive auditobject in separate .csv file

### PR DESCRIPTION
**Pull request by DanBalalan**

### CODE REVIEW

**Comment by DanBalalan** [comment]
bender build

**Comment by BenderArenadata** [comment]
Hey, @DanBalalan! Build has been launched!

**Comment by DanBalalan** [comment]
bender build

**Comment by BenderArenadata** [comment]
Hey, @DanBalalan! Build has been launched!

**Review by a-alferov — APPROVED** [review]

**Pull request merged**
