### PR TITLE
ADCM-2373 Added creating file after upgrade bundle from none config to config with file type field

### PR DESCRIPTION
**Pull request by a-alferov**

### CODE REVIEW

**Comment by a-alferov** [comment]
bender build

**Comment by BenderArenadata** [comment]
Hey, @a-alferov! Build has been launched!

**Comment by a-alferov** [comment]
bender build

**Comment by BenderArenadata** [comment]
Hey, @a-alferov! Build has been launched!

**Review by nagarin — APPROVED** [review]

**Comment by a-alferov** [comment]
bender build

**Comment by BenderArenadata** [comment]
Hey, @a-alferov! Build has been launched!

**Pull request merged**
