### PR TITLE
Release 2022.07.12

### PR DESCRIPTION
**Pull request by kuhella**

### CODE REVIEW

**Comment by kuhella** [comment]
bender build

**Comment by BenderArenadata** [comment]
Hey, @kuhella! Build has been launched!

**Comment by kuhella** [comment]
bender build

**Comment by BenderArenadata** [comment]
Hey, @kuhella! Build has been launched!

**Review by a-alferov — DISMISSED** [review]

**Review by DanBalalan — APPROVED** [review]

**Review by a-alferov — APPROVED** [review]

**Pull request merged**
